### PR TITLE
conda-build: Add 'windows-latest' to conda build workflow

### PR DESCRIPTION
**Pull request by jjerphan**
#### Reference Issues/PRs

Follow-up of #318.
Towards #190.

#### What does this implement/fix? Explain your changes.

Add Windows to the conda build workflow.

#### Any other comments?

It is willingly breaking other configurations on the CI to find one that works for Windows on conda-forge.

### CODE REVIEW

**Comment by jjerphan** [comment]
[pcre cannot be linked on Windows for now](https://github.com/man-group/ArcticDB/actions/runs/5179108802/jobs/9331509094#step:6:402), eventhough [it apparently is resolved](https://github.com/man-group/ArcticDB/actions/runs/5179108802/jobs/9331509094#step:6:262).

There's no CMake configuration for the version of pcre distributed on conda-forge for Windows.

https://github.com/conda-forge/pcre-feedstock/pull/24 is an attempt to improve this build for Windows.

**Comment by jjerphan** [comment]
[pcre cannot be linked on Windows for now](https://github.com/man-group/ArcticDB/actions/runs/5179108802/jobs/9331509094#step:6:402), eventhough [it apparently is resolved](https://github.com/man-group/ArcticDB/actions/runs/5179108802/jobs/9331509094#step:6:262).

There's no CMake configuration for the version of pcre distributed on conda-forge for Windows.

https://github.com/conda-forge/pcre-feedstock/pull/24 is improving the build for Windows regarding CMake.

**Comment by jjerphan** [comment]
Currently blocked by folly not distributing a DLL for Windows.

Addressed by https://github.com/conda-forge/folly-feedstock/pull/115.

**Comment by jjerphan** [comment]
I tried many things but I still obtain linker errors.

There are some missing symbols, namely:
```
error LNK2001: unresolved external symbol "private: static char const * const * const google::protobuf::FieldDescriptor::kCppTypeToName" (?kCppTypeToName@FieldDescriptor@protobuf@google@@0QBQEBDB)
error LNK2001: unresolved external symbol "class google::protobuf::internal::ExplicitlyConstructed<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,8> google::protobuf::internal::fixed_address_empty_string" (?fixed_address_empty_string@internal@protobuf@google@@3V?$ExplicitlyConstructed@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@$07@123@A)
error LNK2001: unresolved external symbol "void * const * const google::protobuf::internal::kGlobalEmptyTable" (?kGlobalEmptyTable@internal@protobuf@google@@3QBQEAXB)
error LNK2001: unresolved external symbol "struct google::protobuf::internal::DescriptorTable const descriptor_table_google_2fprotobuf_2fany_2eproto" (?descriptor_table_google_2fprotobuf_2fany_2eproto@@3UDescriptorTable@internal@protobuf@google@@B)
error LNK2001: unresolved external symbol "struct google::protobuf::AnyDefaultTypeInternal google::protobuf::_Any_default_instance_" (?_Any_default_instance_@protobuf@google@@3UAnyDefaultTypeInternal@12@A)
```

The following is used:
 - `libprotobuf==3.20.3`
 - `protobuf==3.20.3`
 - `MSVC 19.36.32535.0`
 - the dynamic runtime specify `/MD`
 
Missing symbols for similar configurations also have been reported in some currently open issues of `protobuf`. such as:
 - https://github.com/protocolbuffers/protobuf/issues/9676 and to 
 - https://github.com/protocolbuffers/protobuf/issues/11479

**Comment by jjerphan** [comment]
Potential cause of failure to have a look at: [the packaging of abseil and libprotobuf](https://pypackaging-native.github.io/background/binary_interface/#abseil) on conda-forge.

**Comment by h-vetinari** [comment]
> Potential cause of failure to have a look at: [the packaging of abseil and libprotobuf](https://pypackaging-native.github.io/background/binary_interface/#abseil) on conda-forge.

I haven't looked at the issues here, but the only hard requirement you need w.r.t. this ATM is to compile with C++17 (or perhaps C++20).

**Comment by jjerphan** [comment]
> I haven't looked at the issues here, but the only hard requirement you need w.r.t. this ATM is to compile with C++17 (or perhaps C++20).

We already compile with C++17, the problem lies in the code-base with some code for headers being inlined unusually via macros (I did have time to have a look at that yet). @Klaim might be able to give more details in this regard.

**Comment by jjerphan** [comment]
Failures might be related to https://github.com/conda-forge/libprotobuf-feedstock/issues/201.

**Pull request closed without merging**
