### PR TITLE
Revert "build: Update to fmt 10 (#1427)"

### PR DESCRIPTION
**Pull request by vasil-pashov**
This reverts commit 75b14e14b433770a118e111ae7bcd31931797672.

Upgrading to fmt 10 breaks MSVS builds. Abseil package fails to build.

#### Checklist

<details>
  <summary>
   Checklist for code changes...
  </summary>
 
 - [ ] Have you updated the relevant docstrings, documentation and copyright notice?
 - [ ] Is this contribution tested against [all ArcticDB's features](../docs/mkdocs/docs/technical/contributing.md)?
 - [ ] Do all exceptions introduced raise appropriate [error messages](https://docs.arcticdb.io/error_messages/)?
 - [ ] Are API changes highlighted in the PR description?
 - [ ] Is the PR labelled as enhancement or bug so it appears in autogenerated release notes?
</details>

### CODE REVIEW

**Review by jamesmunro — APPROVED** [review]

**Comment by jjerphan** [comment]
We need to use fmt 10 to be able to perform other changes. 

I would rather find a way to fix or work around the problem you faced with https://github.com/microsoft/vcpkg/issues/37213.

**Comment by vasil-pashov** [comment]
> We need to use fmt 10 to be able to perform other changes.
> 
> I would rather find a way to fix or work around the problem you faced with [microsoft/vcpkg#37213](https://github.com/microsoft/vcpkg/issues/37213).

Is there anything besides [this](https://github.com/man-group/ArcticDB/commit/62c322f048f97190ffa074f80d5d5ff6bdd9faed) which requires fmt10?

**Comment by jjerphan** [comment]
Updating fmt 10 might be required to perform other changes beyond this one.

As discussed on another channel, the observed issue might be linked to the MSVC-tool chain integration of CMake rather than to vcpkg. I let @vasil-pashov confirm or infirm.

**Comment by jjerphan** [comment]
Indeed, this is being adressed by https://github.com/man-group/ArcticDB/pull/1436.

**Pull request closed without merging**
