### PR TITLE
Create dependabot.yaml

### PR DESCRIPTION
**Pull request by tschm**
This bot will monitor github actions and suggest updates via pull requests.

### CODE REVIEW

**Comment by tschm** [comment]
Updating your Github actions will get rid of the warnings in https://github.com/man-group/ArcticDB/actions/runs/7961423020

Updating them by hand is a very tedious job

**Comment by poodlewars** [comment]
Thanks @tschm and sorry I've only just seen this one.

It looks good to me, if you could just sign the commit per https://github.com/man-group/ArcticDB/blob/master/Individual%20Contributor%20License%20Agreement.md#7-acceptance , drop the merge commits, and rebase on to master then I'm happy to approve and merge this one.

**Comment by tschm** [comment]
Signed-Off By Thomas Schmelzer [thomas.schmelzer@gmail.com](mailto:thomas.schmelzer@gmail.com). By including this sign-off line I agree to the terms of the Contributor License Agreement”

**Comment by tschm** [comment]
@poodlewars Like this?

**Comment by poodlewars** [comment]
> @poodlewars Like this?

Yep, exactly

**Pull request closed without merging**
