### PR TITLE
fix: added __str__ with hidden account key to AzureLibraryAdapter

### PR DESCRIPTION
**Pull request by StageTired**
Hide sensitive data in AzureLibraryAdapter

#### Reference Issues/PRs
* #753

#### What does this implement or fix?
It adds \_\_str\_\_ method. \_\_str\_\_ () will take priority over \_\_repr\_\_ and will thus hide the sensitive information.
#### Any other comments?
I just removed the actual key from the string. If you want something more human readable that achieves the same goal, I can update the output.
#### Checklist

<details>
  <summary>
   Checklist for code changes...
  </summary>
 
 - [ ] Have you updated the relevant docstrings, documentation and copyright notice?
 - [ ] Is this contribution tested against [all ArcticDB's features](../docs/mkdocs/docs/technical/contributing.md)?
 - [ ] Do all exceptions introduced raise appropriate [error messages](https://docs.arcticdb.io/error_messages/)?
 - [ ] Are API changes highlighted in the PR description?
 - [ ] Is the PR labelled as enhancement or bug so it appears in autogenerated release notes?
</details>

### CODE REVIEW

**Comment by poodlewars** [comment]
This looks good, thank you!

Two small things then this should be mergeable,

Please add a unit test

Please sign the commit with the CLA https://github.com/man-group/ArcticDB/blob/master/Individual%20Contributor%20License%20Agreement.md

**Comment by StageTired** [comment]
> This looks good, thank you!
> 
> Two small things then this should be mergeable,
> 
> Please add a unit test
> 
> Please sign the commit with the CLA https://github.com/man-group/ArcticDB/blob/master/Individual%20Contributor%20License%20Agreement.md

I had to update \_\_repr\_\_ instead because Arctic specificaly calls repr inside itself.
https://github.com/man-group/ArcticDB/blob/23b3b943b7c4a10889a563a063b2a616fe00d9fa/python/arcticdb/arctic.py#L108

Can you recheck it? I also add one test. Idk if it's good enough?

**Comment by StageTired** [comment]
Squashed two commits.

**Review by poodlewars — APPROVED** [review]

**Comment by poodlewars** [comment]
Thanks so much for your contribution to the project @StageTired - I've merged your change.

**Pull request merged**
