### PR TITLE
Use Remotery v1.2.1

### PR DESCRIPTION
**Pull request by jjerphan**
### Relevant issues

Related to https://github.com/man-group/ArcticDB/issues/168.

### Context

Packaging Remotery on conda-forge necessitates using [one of the releases](https://github.com/Celtoys/Remotery/releases/tag/v1.2.1), yet [Remotery as vendored in ArcticDB](https://github.com/man-group/ArcticDB/tree/master/cpp/arcticdb) corresponds to [Remotery@c9f6fae](https://github.com/Celtoys/Remotery/tree/c9f6fae0ecec8beb05310893d87ad1cde0be9373); and `c9f6fae` does not correspond to a tag or a version (it predates [the first release of Remotery](https://github.com/Celtoys/Remotery/releases/tag/v1.0.0)).

This PR update Remotery to v1.2.1 is a preliminary step before unvendoring it from `cpp/third_party` and before using Remotery v1.2.1 from conda-forge 

### Comments and questions

The files simply have been copied from https://github.com/Celtoys/Remotery/tree/v1.2.1, with the `.github` subfolder removed and the `CMakeLists.txt` left unchanged. 

:question: Must some new files be removed as well?
:question: Must modifications made to files in `cpp/third_party/Remotery/vis/` be reverted?

Local runs of the C++ test suites using `test_unit_arcticdb` and `arcticdb_rapidcheck_tests` are successful on my machine.

```
./test_unit_arcticdb
# ... 
[----------] Global test environment tear-down
[==========] 248 tests from 71 test suites ran. (113836 ms total)
```

```
./arcticdb_rapidcheck_tests
# ...
[----------] Global test environment tear-down
[==========] 14 tests from 6 test suites ran. (5209 ms total)
```

:question: Are there other checks to perform before updating this vendored dependence?

### CODE REVIEW

**Comment by willdealtry** [comment]
I'm happy to update to a proper release of Remotery. The previous situation came about purely because as you point out our use of Remotery predated any official releases at all, and if memory serves there was no CMakeLists at that time either - the Remotery files were intended to be directly included in your project. 

We have no specific requirements for the visualizer, let's just use a recent one.

**Comment by jjerphan** [comment]
> if memory serves there was no CMakeLists at that time either

Yes, we are bringing [support for CMake upstream](https://github.com/Celtoys/Remotery/pull/245/) directly. After this support, Remotery will be packageable on conda-forge. It will have to be packaged under two different packages on conda-forge for the dynamic and static libraries respectively. Transitioning to a package on conda-forge should be straightforward given a successful upgrade with this PR. 

Side note: the CI seems blocked. I have tried to close and reopen this PR to see if it could be triggered but it has not.

**Comment by jjerphan** [comment]
I've rebased this branch on `master` and force-pushed to integrate 2f8bbdb69f1e1193f45cb40f892f13a2189fc498 which should resolve solve problems with the test suite.

**Comment by jjerphan** [comment]
Closing this PR for https://github.com/man-group/ArcticDB/pull/310.

**Pull request closed without merging**
