### PR TITLE
Docs workflow fixes. 

### PR DESCRIPTION
**Pull request by jamesmunro**
Add write permission, use tag name (v prefix) and require environment.

### CODE REVIEW

**Comment by jamesmunro** [comment]
Trying to fix this permissions issue: https://github.com/man-group/ArcticDB/actions/runs/6743539659/job/18331628695#step:8:41

**Comment by jamesmunro** [comment]
With the fixes here I've managed to build the [branch ](https://github.com/man-group/ArcticDB/tree/docs-pages) and preview in cloudflare using two versions, 4.1 and master.

https://d4199475.arcticdb-docs.pages.dev/

**Comment by poodlewars** [comment]
> With the fixes here I've managed to build the [branch ](https://github.com/man-group/ArcticDB/tree/docs-pages) and preview in cloudflare using two versions, 4.1 and master.
> 
> https://d4199475.arcticdb-docs.pages.dev/

Why can't I see the versions dropdown on this deployment?

**Comment by jamesmunro** [comment]
> > With the fixes here I've managed to build the [branch ](https://github.com/man-group/ArcticDB/tree/docs-pages) and preview in cloudflare using two versions, 4.1 and master.
> > https://d4199475.arcticdb-docs.pages.dev/
> 
> Why can't I see the versions dropdown on this deployment?

Not totally sure.  Maybe because there isn't two stable versions.

If you go to `dev` you can see it: https://d4199475.arcticdb-docs.pages.dev/dev/

**Comment by jamesmunro** [comment]
@poodlewars 
> Why can't I see the versions dropdown on this deployment?

Okay.  Figured it out.  It's because 4.1.0 builds with the 4.1.0 mkdocs.yml into the 4.1.0 subdir.  
4.1.0 didn't have versioning, so I need backport versioning it for it to appear.

**Review by poodlewars — APPROVED** [review]

**Pull request merged**
